language: cpp
os: linux
compiler: gcc

env:
  global:
    - CMAKE_VER=2.8.9
    - CMAKE_CACHE_DIR=~/.cmake

cache:
  directories:
    - $CMAKE_CACHE_DIR

before_install:
  - sudo apt-get -qq update
  - sudo apt-get --no-install-recommends install -y doxygen # libcurl4-openssl-dev (already available in Travis CI environment)
  - if [ ! $(git config --get user.email) ]; then $(git config --global user.email 'user@example.com'); fi
  - if [ ! $(git config --get user.name) ]; then $(git config --global user.name 'Travis CI'); fi

install:
  # Is CMake available in the cache?
  - >-
    if [ ! -d "$CMAKE_CACHE_DIR"/* ] || [ ! -f "$CMAKE_CACHE_DIR/.version" ] || [ ! $(cat "$CMAKE_CACHE_DIR/.version") = "$CMAKE_VER" ]; then
      echo "CMake not in cache or wrong version"
      rm -rf "$CMAKE_CACHE_DIR/*"
      cd
      git clone https://github.com/kitware/cmake
      cd cmake
      git checkout "tags/v$CMAKE_VER"
      mkdir build
      cd build
      cmake .. -DBUILD_CursesDialog:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DCMAKE_USE_SYSTEM_CURL:BOOL=ON -DCMAKE_USE_OPENSSL:BOOL=ON -DCMAKE_INSTALL_PREFIX=$CMAKE_CACHE_DIR
      make -j2
      make install
      echo "$CMAKE_VER" > "$CMAKE_CACHE_DIR/.version"
    else
      echo "CMake directory found in cache (version $(cat "$CMAKE_CACHE_DIR/.version"))"
    fi

  # Shadow packaged CMake
  - export PATH=$CMAKE_CACHE_DIR/bin/:$PATH
  - export CMAKE_MODULE_PATH="$(find "$CMAKE_CACHE_DIR/share" -maxdepth 1 -type d -name cmake-* | head -n 1)/Modules"
  - echo "$CMAKE_MODULE_PATH"
  - cmake -version

  # Download and configure YARP
  - cd
  - git clone --depth=1 https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake .. -DSKIP_ACE:BOOL=ON
  - export YARP_DIR=$PWD

before_script:
  - cd $TRAVIS_BUILD_DIR
  - ./project-generator.sh < test_program_answers.txt
  - cd $(tail -n 1 test_program_answers.txt)

script:
  - scripts/package/make_package.sh
